---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  google_client_email: <%= ENV['GOOGLE_CLIENT_EMAIL'] %>
  google_key_location: <%= ENV['GOOGLE_KEY_LOCATION'] %>
  google_project: <%= ENV['GOOGLE_PROJECT'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest
