AllCops:
  Exclude:
    - vendor/**/*
    - Guardfile
    - Rakefile

AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FileName:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 9
